### ISSUE TITLE
is this supposed to be in pypi?

### ISSUE THREAD

**Issue by leith-bartrich** [python-cmd2/cmd2-submenu#1]
The readme suggests that to install I should run:

pip install cmd2-submenu

And the changelog on the main cmd2 project reads:

Submenu support has been moved to a new cmd2-submenu plugin. If you use submenus, you will need to update your dependencies and modify your imports.

Both of these together seem to suggest that cmd2-submenu should be in pypi.  Yet, if I search for it, it's not showing up.  And indeed, the given pip command fails; as one would expect, given the listing isn't showing up.  Similarly, adding "cmd2-submenu" to a setup.py file yields the same results.

I am trying to update my setup.py as you suggest but it's unclear if I should be hacking it up to pull directly from this GitHub repository/branch or if it's supposed to be listed in pypi.

**Comment by tleonhardt** [comment]
@leith-bartrich Yes, this is supposed to be in PyPI.  It appears to be an oversight on our part.  Thanks for pointing this out!

@kotfu @kmvanbrunt Would one of you have time to test to make sure that this plug-in still works properly with the latest version of cmd2 and if so publish a release to PyPI and if not create an Issue specifying what the bug is so we can fix it?  I’m still out of town without my computer.

**Comment by kotfu** [comment]
Oops. I forgot to publish this to pypi. I’ll do it later today.

**Comment by kotfu** [comment]
Version 0.2.0 uploaded to pypi.
